-------- EMPLOYEE INFO --------
SELECT DISTINCT PMEMPLP.EMPID AS [EMPLOYEE ID]
	, PMEMPLP.EMFN 'FIRST NAME'
	, PMEMPLP.EMLN 'LAST NAME'
	, PMEMPLP.EMMAIL 'EMAIL'
	, CONVERT(VARCHAR(10),CAST(CAST(PMEMPLP.EMDHIR AS VARCHAR(10)) AS DATE),101) 'HIRE DATE'
	, LEFT(CONVERT(VARCHAR(10),CAST(CAST(PMEMPLP.EMBDAY AS VARCHAR(10)) AS DATE),101),5) 'BIRTH DATE'
	,

	-------- ROLE --------
	CASE
		WHEN RTRIM(LTRIM(PMEMPLP.EMPID)) IN (
		'658313', -- AMANDA SAWAGED
		'652365',-- ALEX GONTAREK
		'401471', --DONITA KEMMERER
		'629605', -- DELLA WATERS
		'510487',-- MICHAEL PAUL
		'621155', -- GINA LOVE
		'676509',-- JOSH ADLER
		'623859', --ROBERT ESTRADA
		'557902', -- TIFFANY LILLE
		'666340', -- SAM THOMAS
		'640280', -- SAVANNAH CAMP
		'673025', --SHARON GRUNER
		'643376', --APRYL BARRETT
		'590909', --ALEX EDWARDS
		'640282', -- LORI DUCKWORTH
		'690509', --ASHLEY EVANS
		'639347' --BRANDON AKARD
		) THEN 'ADMIN' WHEN PMEMPLP.EMJBCD = 'DRV' THEN 'EMPLOYEE' WHEN PMEMPLP.EMJBCD = 'OFF' THEN 'GROUP MANAGER' WHEN PMEMPLP.EMJBCD = 'EXE' THEN 'EXECUTIVE MANAGER' ELSE ''
	END AS 'ROLE'
	, 'US' AS 'COUNTRY CODE'
	, PMEMPLP_1.EMPID 'SUPERVISOR ID'
	, 'EN' AS 'LANGUAGE'
	, CASE
		WHEN PMEMPLP.EMJBCD = 'DRV' THEN LEFT(PMEMPLP.EMDCG,1) WHEN PMEMPLP.EMJBCD = 'OFF' THEN LEFT(PRPMS.PRL02,1) ELSE ''
	END AS '#COST CENTER'
	, CASE
		WHEN PMEMPLP.EMJBCD = 'DRV' THEN PCG.PCCGP ELSE 'OFFICE'
	END AS '#PAYROLL GROUP'
	, CASE
		WHEN PMEMPLP.EMJBCD = 'DRV' THEN CGM.CGDSC ELSE 'OFFICE'
	END AS '#PAYROLL GROUP DESCRIPTION'
	, PMEMPLP.EMDCG #CONTROLGROUP
	, PMEMPLP.EMJBCD '#SECURITY GROUP'
	, CASE
		WHEN PMEMPLP.EMJBCD IN ('OFF','EXE') THEN PRPMS.PRTITL WHEN (
			PMEMPLP.EMJBCD IN ('DRV')
			AND PMEMPLP.EMJBDS = 'DTE')      THEN 'DRIVER TRAINEE' WHEN (
			PMEMPLP.EMJBCD IN ('DRV')
			AND PMEMPLP.EMJBDS = 'DTR')      THEN 'DRIVER TRAINER' ELSE 'DRIVER'
	END AS '#JOBTITLE'
	, ( SELECT EMPAT_ATT_TXT
        	FROM PSA.DBO.SMFD35_XPSFILE_EMPATMP
        WHERE EMPAT_CO# = PMEMPLP.EMCM
        	AND EMPAT_EMP_SS# = PMEMPLP.EMES#
        	AND EMPAT_DRV_ATTR = 'AZUREEMAIL') AS 'USERNAME'
	, '' AS 'PASSWORD'

	FROM PSA.DBO.SMFD35_XPSFILE_PMEMPLP                            PMEMPLP(NOLOCK)
		LEFT JOIN PSA.[DBO].[SMFD35_XPSFILE_PAYROLL_CONTROL_GROUP] PCG (NOLOCK) ON PMEMPLP.EMES# = PCG.PCSS#
			AND PCEXPD = '99999999'
		LEFT JOIN PSA.[DBO].[SMFD35_XPSFILE_CONTROL_GROUP_MASTER]  CGM ON CGM.CGCDE = PCG.PCCGP
			AND CGM.CGDIV = PCG.PCDIV
			AND CGM.CGEXPD='99999999'
			AND CGM.CGTYPE='PR'

		LEFT JOIN PSA.DBO.SMFD35_HRDBFA_PRPMS                      PRPMS ON CONCAT(0,PMEMPLP.EMCM) = PRPMS.PRER
			AND PMEMPLP.EMPID = PRPMS.PREN
		LEFT JOIN PSA.DBO.SMFD35_HRDBFA_PEPOG                      PEPOG ON PRPMS.PRER = PEPOG.OGER
			AND PRPMS.PRPOS = PEPOG.OGPOS
		LEFT JOIN PSA.DBO.SMFD35_XPSFILE_PMEMPLP                   PMEMPLP_1(NOLOCK) ON PMEMPLP.EMCM = PMEMPLP_1.EMCM
			AND PMEMPLP.EMSPES = PMEMPLP_1."EMES#"
		LEFT JOIN PSA.DBO.SMFD35_HRDBFA_PRPMS                      PRPMS_1 ON CONCAT(0,PMEMPLP_1.EMCM) = PRPMS_1.PRER
			AND PMEMPLP_1.EMPID = PRPMS_1.PREN

WHERE
	--FAMILY DOLLAR DUNCAN, FAMILY DOLLAR MARIANNA, RYDER JACKSONVILLE, WALMART GORDONSVILLE

	(RTRIM(LTRIM(PMEMPLP.EMPID)) IN (
	'412791', -- JUSTIN HARNESS
	'658313', -- AMANDA SAWAGED
	'652365' ,-- ALEX GONTAREK
	'401471', --DONITA KEMMERER
	'629605', -- DELLA WATERS
	'586527', --GREG AFTUNG
	'435174', -- ERIC HOLCOMB
	'449364', -- ASHLEY ELLISON
	'585540', -- ADAM POORE
	'548100',-- SHANE WEEKS
	'431593',-- DAN PERKINS
	'410340', -- CLAYTON KIBLER
	'669621', --MATTHEW HALULKO
	'510487', -- MICHAEL PAUL
	'621155',-- GINA LOVE
	'623859', -- ROBERT ESTRADA
	'557902', --TIFFANY LILLIE
	'676509', -- JOSH ADLER
	'640280', -- SAVANNAH SMTIH
	'673025', --SHARON GRUNER
	'666340', -- SAM THOMAS
	'643376', --APRYL BARRETT
	'590909', --ALEX EDWARDS
	'640282', -- LORI DUCKWORTH
	'690509', --ASHLEY EVANS
	'639347' --BRANDON AKARD
	) )

	OR (
		(PMEMPLP.EMESTS NOT IN ('ZZ'))
		AND PMEMPLP.EMCM IN ('01')
		AND PMEMPLP.EMJBDS <> 'DTE'
		AND (
			(
				PMEMPLP.EMJBCD IN ('DRV')
				AND PMEMPLP.EMDCG LIKE ('D%'))
			OR (
				PMEMPLP.EMJBCD IN ('OFF','EXE')
				AND PRPMS.PRL02 = ('DED')))
		AND (
			(
				PMEMPLP.EMJBCD IN ('DRV')
				AND PCG.PCCGP IN ('185','185P','112','112P','280','303'))
			OR (
				PMEMPLP.EMJBCD IN ('OFF','EXE')
				AND PRPMS.PRL04 IN ('FFL', 'WGV','FOK','DPF')))
		AND (
			PMEMPLP.EMJBCD = 'DRV'
			OR (
				PMEMPLP.EMJBCD IN ('OFF')
				AND PEPOG.OGPLVL IN ('35','31')))
		AND PMEMPLP.EMDEPT <> 'SHP'
		AND PMEMPLP.EMPCO <> 'XX')